version: "3.2"

services:
    crm-app:
        build: 
            context: .
            dockerfile: dockerfile
        image: crm-image
        restart: unless-stopped
        container_name: crm-services
        ports:
            - "3002:3002"
        volumes:
            - type: bind
              source: ./
              target: /usr/src/app/
        networks:
            - app-network
    
    nginx:
        image: nginx
        restart: unless-stopped
        user: root
        ports:
            - "80:80"
        depends_on:
            - crm-app
        links:
            - crm-app
        volumes:
            - type: bind
              source: ./nginx.conf
              target: /etc/nginx/conf.d/crm.conf
        networks:
            - app-network
networks:
    app-network: